version: '3'

networks:
  nextjs:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - nextjs